### ISSUE TITLE
Aria understanding questions

### ISSUE THREAD

**Issue by Kukk0006** [abhaysharma/accessible-me#1]
@abhaysharma Hi Abhay,

I have done the initial formatting on this week's assignment.  I have a few questions before I go into styling and formatting further.
My main one is if I am using ARIA correctly.  Wave says I have 3 ARIA tags, it seems like it isn't counting the roles that I've added.  I am going to research more, but would like your input if I am along the right tracks.  
The other one relates to my question in class.  For the owner and address sections, should I be using a aria-label for each of the itemprop that essentially shares the same name. ie (line 63)<li itemprop="name" aria-label="name">  or is that one overly redundant since the text that shows says Name: John Doe?
Would it make sense though to do that on the span tags for the address?

Thank you

**Comment by abhaysharma** [comment]
@Kukk0006 you have submitted this issue in the main repository and not in your forked version. Please create the issue in your forked version so I can see your code.

**Comment by Kukk0006** [comment]
Thank you, Abhay.  I see what and how I did it.  I have since fixed the issue and submitted the issue on my forked version of the assignment.



Cassie Kukkonen
#041-039-803
Interactive Media Design
Level 2 Winter 2023
________________________________
